# Copyright (c) 2020 Famedly GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

stages:
  - test
  - deploy

coverage:
  image: archlinux:latest
  stage: test
  needs: []
  coverage: '/^\s+lines.+: (\d+.\d*%)/'
  script:
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S dart firefox libolm valgrind
    - useradd -m test
    - chown -R 'test:' '.'
    - su -c ./scripts/prepare.sh test
    - su -c ./scripts/test.sh test
  artifacts:
    paths:
      - coverage/

code_analyze:
  image: cirrusci/flutter
  stage: test
  needs: []
  allow_failure: true
  script:
    - flutter analyze

pages:
  stage: deploy
  needs: []
  image: cirrusci/flutter
  script:
    - ./scripts/doc.sh
    - mv doc/api public
  artifacts:
    paths:
      - public
  only:
    - main
