# Copyright (c) 2020 Famedly GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

include:
  - project: "famedly/company/frontend/ci-templates"
    ref: main
    file: "/all.yml"

image:
  name: google/dart

stages:
  - test
  - deploy

coverage:
  image: archlinux:latest
  stage: test
  needs: []
  coverage: '/^\s+lines.+: (\d+.\d*%)/'
  script:
    - echo "Server = https://geo.mirror.pkgbuild.com/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
    - |
      cat <<EOF >> /etc/pacman.conf
      # Testing Repositories
      
      [testing-debug]
      Include = /etc/pacman.d/mirrorlist
      
      [community-testing-debug]
      Include = /etc/pacman.d/mirrorlist
      
      [multilib-testing-debug]
      Include = /etc/pacman.d/mirrorlist
      
      # Stable repositories
      
      [core-debug]
      Include = /etc/pacman.d/mirrorlist
      
      [extra-debug]
      Include = /etc/pacman.d/mirrorlist
      
      [community-debug]
      Include = /etc/pacman.d/mirrorlist
      
      [multilib-debug]
      Include = /etc/pacman.d/mirrorlist
      EOF
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S dart firefox libolm valgrind lcov glibc-debug libolm-debug
    - useradd -m test
    - chown -R 'test:' '.'
    - su -c ./scripts/prepare.sh test
    - su -c ./scripts/test.sh test
  artifacts:
    paths:
      - coverage/

pages:
  image: cirrusci/flutter
  stage: deploy
  needs: []
  script:
    - ./scripts/doc.sh
    - mv doc/api public
  artifacts:
    paths:
      - public
  only:
    - main

dry_run:
  stage: deploy
  script:
    - dart pub publish --dry-run

pub_dev:
  stage: deploy
  script:
    - |
      if [ -z "${PUB_DEV_CREDENTIALS}" ]; then
        echo "Missing PUB_DEV_CREDENTIALS environment variable"
        exit 1
      fi
    - cp "${PUB_DEV_CREDENTIALS}" ~/.pub-cache/credentials.json
    - dart pub get
    - dart pub publish --force
  rules:
    - if: $CI_COMMIT_TAG
