# Copyright (c) 2020 Famedly GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

name: olm
version: 0.0.0
dependencies:
  js: ^0.6.0
  ffi: ^0.1.3
  test: ^1.11.0
dev_dependencies:
  test_coverage: ^0.4.0
