# Copyright (c) 2020 Famedly GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

name: olm
description: Dart bindings for Olm
author: Famedly GmbH <info@famedly.com>
homepage: https://famedly.gitlab.io/libraries/dart-olm/
repository: https://gitlab.com/famedly/libraries/dart-olm

environment:
  sdk: ">=2.7.0 <3.0.0"

version: 1.2.0
dependencies:
  js: ^0.6.0
  ffi: ^0.1.3
  test: ^1.9.0
dev_dependencies:
  test_coverage: ^0.4.0
