on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
  merge_group:

      
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
      
      
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: cat .github/workflows/versions.env >> $GITHUB_ENV
      - uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
        with:
          sdk: ${{ env.dart_version }}
      - name: Run tests
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends --no-install-suggests -y lcov valgrind
          ./scripts/prepare_native.sh
          ./scripts/prepare_js.sh
          ./scripts/test.sh
      - name: Codecov - Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage/lcov.info
